export const MOCK_USER = {
  id: 'user_001',
  username: 'Samuelegin',
  displayName: 'Samuel Egin',
  email: 'samuelegin@gmail.com',
  avatarUrl: null,
  bio: 'Full-stack Web3 developer. Solidity + React. Building on Base.',
  roleTags: ['Lead Engineer', 'Smart Contract Dev'],
  skillTags: ['Solidity', 'React', 'Node.js', 'TypeScript', 'DeFi'],
  baseWallet: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
  solanaWallet: null,
  socials: { twitter: 'samuel', github: 'samuelegin' },
  blueTick: false,
  goldTick: false,
  kycVerified: false,
  totalEarningsUsd: 12450,
  piScore: 94,
  totalXp: 340,
}

export const MOCK_PODS = [
  {
    id: 'pod_001',
    name: 'DeFi Builders',
    description: 'A tight pod of 3 building DeFi primitives on Base.',
    status: 'active',
    myRole: 'admin',
    memberCount: 3,
    piScore: 91,
    xp: 4,
    earningsUsd: 8200,
    maxMembers: 5,
    settlementChain: 'base',
    roles: ['Lead Engineer', 'Smart Contract Dev', 'UI Designer'],
    splits: [
      { role: 'Lead Engineer',       percentage: 50 },
      { role: 'Smart Contract Dev',  percentage: 30 },
      { role: 'UI Designer',         percentage: 20 },
    ],
    members: [
      { id: 'user_001', displayName: 'Samuel',    role: 'Lead Engineer',      isAdmin: true,  piScore: 94, xp: 4 },
      { id: 'user_002', displayName: 'Maliel',   role: 'Smart Contract Dev', isAdmin: false, piScore: 88, xp: 3 },
      { id: 'user_003', displayName: 'Josh',      role: 'UI Designer',        isAdmin: false, piScore: 82, xp: 2 },
    ],
    popRecords: [
      { id: 'pr_a1', workType: 'Engineering', jobTitle: 'DEX Frontend Redesign', milestones: 3, delivery: 'On time', chainAnchor: 'Base', score: 95, piScore: 95, earnedUsd: 4500, issuedAt: '2026-01-15T00:00:00Z' },
    ],
    projectAssigned: true,
    createdAt: '2025-09-10T10:00:00Z',
    deals: [
      { id: 'deal_001', title: 'DEX Frontend Redesign',      status: 'active',    budgetUsd: 4500, category: 'Engineering', timeline: '6 weeks' },
      { id: 'deal_002', title: 'Smart Contract Audit',        status: 'pending',   budgetUsd: 3700, category: 'Engineering', timeline: '2 weeks' },
      { id: 'deal_003', title: 'Liquidity Pool UI',           status: 'completed', budgetUsd: 2800, category: 'Design',      timeline: '4 weeks' },
    ],
  },
  {
    id: 'pod_002',
    name: 'DAO Content Crew',
    description: 'Community growth and content strategy for Web3 protocols.',
    status: 'forming',
    myRole: 'member',
    memberCount: 2,
    piScore: null,
    xp: 0,
    earningsUsd: 0,
    maxMembers: 4,
    settlementChain: 'solana',
    roles: ['Content Strategist', 'Community Lead'],
    splits: [
      { role: 'Content Strategist', percentage: 55 },
      { role: 'Community Lead',     percentage: 45 },
    ],
    members: [
      { id: 'user_004', displayName: 'Sensei',   role: 'Content Strategist', isAdmin: true,  piScore: 79, xp: 2 },
      { id: 'user_001', displayName: 'Maliel',    role: 'Community Lead',     isAdmin: false, piScore: 94, xp: 4 },
    ],
    projectAssigned: false,
    createdAt: '2025-11-20T10:00:00Z',
    deals: [],
  },
  {
    id: 'pod_003',
    name: 'Chain Analytics',
    description: 'On-chain data analysis and dashboards for protocols.',
    status: 'completed',
    myRole: 'admin',
    memberCount: 3,
    piScore: 96,
    xp: 5,
    earningsUsd: 11800,
    maxMembers: 3,
    settlementChain: 'base',
    roles: ['Lead Engineer', 'Research Analyst', 'DevOps'],
    splits: [
      { role: 'Lead Engineer',    percentage: 45 },
      { role: 'Research Analyst', percentage: 35 },
      { role: 'DevOps',           percentage: 20 },
    ],
    members: [
      { id: 'user_001', displayName: 'Samuel',      role: 'Lead Engineer',    isAdmin: true,  piScore: 94, xp: 4 },
      { id: 'user_005', displayName: 'Josh',         role: 'Research Analyst', isAdmin: false, piScore: 85, xp: 3 },
      { id: 'user_006', displayName: 'Maliel',      role: 'DevOps',           isAdmin: false, piScore: 80, xp: 2 },
    ],
    popRecords: [
      { id: 'pr_c1', workType: 'Research',    jobTitle: 'Protocol TVL Dashboard', milestones: 3, delivery: 'On time', chainAnchor: 'Base', score: 96, piScore: 96, earnedUsd: 6000, issuedAt: '2025-11-15T00:00:00Z' },
      { id: 'pr_c2', workType: 'Research',    jobTitle: 'Wallet Flow Analytics',  milestones: 2, delivery: 'Early',   chainAnchor: 'Base', score: 94, piScore: 94, earnedUsd: 5800, issuedAt: '2025-10-02T00:00:00Z' },
      { id: 'pr_c3', workType: 'Engineering', jobTitle: 'DEX Smart Contracts',    milestones: 4, delivery: 'On time', chainAnchor: 'Base', score: 91, piScore: 91, earnedUsd: 4200, issuedAt: '2025-08-20T00:00:00Z' },
    ],
    projectAssigned: false,
    createdAt: '2025-06-01T10:00:00Z',
    deals: [
      { id: 'deal_009', title: 'Protocol TVL Dashboard', status: 'completed', budgetUsd: 6000, category: 'Research', timeline: '5 weeks' },
      { id: 'deal_010', title: 'Wallet Flow Analytics',  status: 'completed', budgetUsd: 5800, category: 'Research', timeline: '4 weeks' },
    ],
  },
]

export const MOCK_NOTIFICATIONS = [
  { id: 'n1', type: 'job_assigned',    title: 'You were matched to DEX Frontend Redesign',          body: 'BaseSwap Protocol accepted your application. Chat is now open.',   read: false, createdAt: new Date(Date.now() - 1000*60*25).toISOString() },
  { id: 'n2', type: 'funds_released',  title: '$8,200 released to your pod',                        body: 'Chain Analytics completed — payout sent to Base wallet.',          read: false, createdAt: new Date(Date.now() - 1000*60*60*2).toISOString() },
  { id: 'n3', type: 'rating_received', title: 'New 5★ rating from OmniLink Protocol',              body: '"Exceptional quality and communication. Will work again."',          read: false, createdAt: new Date(Date.now() - 1000*60*60*5).toISOString() },
  { id: 'n4', type: 'pod_invite',      title: 'Priya Nair invited you to DAO Content Crew',        body: 'Role: Community Lead · Pod on Solana',                             read: true,  createdAt: new Date(Date.now() - 1000*60*60*24).toISOString() },
  { id: 'n5', type: 'work_approved',   title: 'Deliverable approved — Chain Analytics',            body: 'Your TVL dashboard was approved. PI Score incoming.',             read: true,  createdAt: new Date(Date.now() - 1000*60*60*48).toISOString() },
  { id: 'n6', type: 'pop_minted',      title: 'PI Score #7 recorded on Base',                       body: 'PI Score updated. View your PI Scores.',         read: true,  createdAt: new Date(Date.now() - 1000*60*60*72).toISOString() },
  { id: 'n7', type: 'pod_invite',      title: 'DeFi Builders pod — new member joined',             body: 'Mike Torres accepted the UI Designer role.',                       read: true,  createdAt: new Date(Date.now() - 1000*60*60*96).toISOString() },
]

export const MOCK_LEADERBOARD = [
  { id: 'user_007', username: '0xdauxun',   displayName: '0xDauxun',   earned: 38400, completedJobs: 24, piScore: 99, blueTick: true,  goldTick: true,  kycVerified: true  },
  { id: 'user_008', username: 'blaqsmith',  displayName: 'Blaqsmith',  earned: 29100, completedJobs: 18, piScore: 97, blueTick: true,  goldTick: false, kycVerified: true  },
  { id: 'user_009', username: 'dwarf_web3', displayName: 'Dwarf of Web3', earned: 24800, completedJobs: 15, piScore: 96, blueTick: true,  goldTick: false, kycVerified: true  },
  { id: 'user_010', username: 'web3bull',   displayName: 'Web3 Bull',  earned: 19500, completedJobs: 13, piScore: 95, blueTick: false, goldTick: false, kycVerified: true  },
  { id: 'user_001', username: 'swyft',      displayName: 'Swyft',      earned: 12450, completedJobs: 9,  piScore: 94, blueTick: false, goldTick: false, kycVerified: false },
  { id: 'user_011', username: 'xammie',     displayName: 'Xammie',     earned: 9800,  completedJobs: 7,  piScore: 90, blueTick: false, goldTick: false, kycVerified: true  },
  { id: 'user_012', username: 'edosa',      displayName: 'Edosa',      earned: 7600,  completedJobs: 6,  piScore: 87, blueTick: false, goldTick: false, kycVerified: false },
  { id: 'user_004', username: '0xxener',    displayName: '0xXener',    earned: 5200,  completedJobs: 5,  piScore: 79, blueTick: false, goldTick: false, kycVerified: false },
  { id: 'user_013', username: 'chidi',      displayName: 'Chidi',      earned: 3900,  completedJobs: 4,  piScore: 75, blueTick: false, goldTick: false, kycVerified: false },
  { id: 'user_014', username: 'kaito_eth',  displayName: 'Kaito Nakamura', earned: 1800, completedJobs: 2, piScore: 68, blueTick: false, goldTick: false, kycVerified: false },
]

export const MOCK_POD_LEADERBOARD = [
  { id: 'pod_001', name: 'Apex Protocol Crew',   memberCount: 4, earned: 52400, completedJobs: 18, piScore: 98, xp: 14, status: 'active'    },
  { id: 'pod_002', name: 'Chain Analytics Guild', memberCount: 3, earned: 38900, completedJobs: 13, piScore: 96, xp: 11, status: 'active'    },
  { id: 'pod_003', name: 'DeFi Builders DAO',     memberCount: 5, earned: 29200, completedJobs: 10, piScore: 94, xp: 8,  status: 'completed' },
  { id: 'pod_004', name: 'Web3 Design Studio',    memberCount: 3, earned: 21800, completedJobs: 9,  piScore: 92, xp: 7,  status: 'active'    },
  { id: 'pod_005', name: 'Solidity Sharks',        memberCount: 4, earned: 15600, completedJobs: 7,  piScore: 90, xp: 5,  status: 'active'    },
  { id: 'pod_006', name: 'Moonlite Frontend Fam', memberCount: 2, earned: 10300, completedJobs: 6,  piScore: 87, xp: 4,  status: 'completed' },
  { id: 'pod_007', name: 'zkProof Collective',    memberCount: 3, earned: 7800,  completedJobs: 4,  piScore: 85, xp: 3,  status: 'active'    },
  { id: 'pod_008', name: 'Infra Nomads',           memberCount: 2, earned: 4200,  completedJobs: 3,  piScore: 78, xp: 2,  status: 'forming'   },
]

export const MOCK_PI_SCORE_RECORDS = [
  { id: 'pi_001', dealTitle: 'Protocol TVL Dashboard', category: 'Research',     piScore: 96, delivery: 'On time', milestones: 3, earnedUsd: 6000,  completedAt: '2025-11-15T00:00:00Z' },
  { id: 'pi_002', dealTitle: 'Wallet Flow Analytics',  category: 'Research',     piScore: 94, delivery: 'Early',   milestones: 2, earnedUsd: 5800,  completedAt: '2025-10-02T00:00:00Z' },
  { id: 'pi_003', dealTitle: 'DEX Smart Contracts',    category: 'Engineering',  piScore: 91, delivery: 'On time', milestones: 4, earnedUsd: 4200,  completedAt: '2025-08-20T00:00:00Z' },
  { id: 'pi_004', dealTitle: 'DeFi App Rebrand',       category: 'Design',       piScore: 89, delivery: 'Late',    milestones: 2, earnedUsd: 3200,  completedAt: '2025-07-10T00:00:00Z' },
]

export const MOCK_XP_TASKS = [
  { id: 'xp_001', task: 'Completed KYC Verification',       xp: 50,  completedAt: '2025-09-12T10:00:00Z', icon: 'bi-shield-check',      category: 'Verification' },
  { id: 'xp_002', task: 'Connected Base Wallet',            xp: 30,  completedAt: '2025-09-10T09:00:00Z', icon: 'bi-wallet2',           category: 'Onboarding'   },
  { id: 'xp_003', task: 'Completed Profile Setup',          xp: 25,  completedAt: '2025-09-10T09:30:00Z', icon: 'bi-person-check',      category: 'Onboarding'   },
  { id: 'xp_004', task: 'First Deal Application Sent',      xp: 40,  completedAt: '2025-09-15T14:00:00Z', icon: 'bi-send-check',        category: 'Engagement'   },
  { id: 'xp_005', task: 'Joined First Pod',                 xp: 35,  completedAt: '2025-09-10T11:00:00Z', icon: 'bi-people',            category: 'Collaboration'},
  { id: 'xp_006', task: 'Referred a Talent',                xp: 60,  completedAt: '2025-10-05T16:00:00Z', icon: 'bi-person-plus',       category: 'Growth'       },
  { id: 'xp_007', task: 'Completed Skill Assessment',       xp: 45,  completedAt: '2025-10-18T10:00:00Z', icon: 'bi-clipboard-check',   category: 'Skills'       },
  { id: 'xp_008', task: 'Added Social Links',               xp: 15,  completedAt: '2025-09-11T08:00:00Z', icon: 'bi-link-45deg',        category: 'Onboarding'   },
  { id: 'xp_009', task: 'Submitted First Deliverable',      xp: 40,  completedAt: '2025-11-02T12:00:00Z', icon: 'bi-upload',            category: 'Engagement'   },
]

// Project owner side
export const MOCK_PROJECT = {
  id: 'proj_001',
  username: 'apexium',
  displayName: 'Apexium',
  email: 'team@apexium.io',
  bio: 'Leading Web3 job agency connecting top talent with innovative blockchain projects. Building the future of decentralized work.',
  avatarUrl: null,
  baseWallet: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
  socials: { website: 'apexium.io', twitter: 'apexium' },
  blueTick: true,
  goldTick: false,
}

export const MOCK_PROJECT_JOBS = [
  {
    id: 'pjob_001',
    title: 'DEX Frontend Redesign',
    category: 'Engineering',
    status: 'active',
    budgetUsd: 4500,
    timeline: '6 weeks',
    matchType: 'manual',
    applicantCount: 8,
    deadline: '2026-04-28T00:00:00Z',
  },
  {
    id: 'pjob_002',
    title: 'Smart Contract Audit — v2',
    category: 'Engineering',
    status: 'open',
    budgetUsd: 3700,
    timeline: '2 weeks',
    matchType: 'system',
    applicantCount: 3,
    deadline: '2026-04-15T00:00:00Z',
  },
  {
    id: 'pjob_003',
    title: 'Liquidity Pool UI',
    category: 'Design',
    status: 'completed',
    budgetUsd: 2800,
    timeline: '4 weeks',
    matchType: 'manual',
    applicantCount: 11,
    deadline: '2026-02-01T00:00:00Z',
  },
  {
    id: 'pjob_004',
    title: 'Tokenomics Research Report',
    category: 'Research',
    status: 'draft',
    budgetUsd: 1500,
    timeline: '2 weeks',
    matchType: 'manual',
    applicantCount: 0,
    deadline: '2026-05-30T00:00:00Z',
  },
]

export const MOCK_PREMIUM_CONFIG = {
  blue: {
    key: 'blue',
    name: 'Blue',
    tagline: 'Verified talent',
    color: '#3B82F6',
    bg: '#EFF6FF',
    border: '#BFDBFE',
    darkBg: 'rgba(59,130,246,0.12)',
    imgSrc: '/images/deals-icon.png',
    price: 9,
    perks: [
      'Blue badge on your public profile',
      'Priority visibility in pod matching',
      'Verified status on the leaderboard',
      'Early access to premium deals',
      'Standard support',
    ],
  },
  gold: {
    key: 'gold',
    name: 'Gold',
    tagline: 'Elite talent',
    color: '#F59E0B',
    bg: '#FFFBEB',
    border: '#FDE68A',
    darkBg: 'rgba(245,158,11,0.12)',
    imgSrc: '/images/wallet-earnings.png',
    price: 29,
    badge: 'Most value',
    perks: [
      'Gold badge — highest trust signal',
      'Top placement in all deal searches',
      'KYC fast-track for high-value deals',
      'Dedicated account manager',
      'Revenue share on referrals',
      'Exclusive Gold-only deal access',
    ],
  },
}
// ─── MARKETPLACE DEALS ────────────────────────────────────────
export const MOCK_DEALS = [
  {
    id: 'mk_001',
    title: 'DEX Frontend Redesign',
    category: 'Engineering',
    description: 'Redesign the swap interface and liquidity pools UI for a Base-native DEX. Must be mobile-first, support WalletConnect, and achieve <200ms interaction response times. Figma designs provided.',
    budgetUsd: 8500,
    paymentStructure: 'milestone',
    chain: 'base',
    requiredType: 'pod',
    deadline: new Date(Date.now() + 1000*60*60*24*18).toISOString(),
    applicantCount: 14,
    kpis: ['Mobile-first', 'WalletConnect', 'Figma-ready', '<200ms response'],
    milestones: [
      { id: 1, title: 'Wireframes & design review', pct: 20, dueWeek: 1 },
      { id: 2, title: 'Core swap UI implementation', pct: 50, dueWeek: 4 },
      { id: 3, title: 'QA, audit & final handoff',   pct: 30, dueWeek: 6 },
    ],
    projectOwnerName: 'BaseSwap Protocol',
    projectOwnerVerified: true,
    myStatus: 'accepted',
  },
  {
    id: 'mk_002',
    title: 'Smart Contract Security Audit',
    category: 'Engineering',
    description: 'Full audit of a 4-contract DeFi lending protocol on Base. Must include static analysis, manual review, and a written report with severity classifications. Experience with Foundry required.',
    budgetUsd: 12000,
    paymentStructure: 'milestone',
    chain: 'base',
    requiredType: 'pod',
    deadline: new Date(Date.now() + 1000*60*60*24*10).toISOString(),
    applicantCount: 7,
    kpis: ['Foundry', 'Static analysis', 'Written report', 'Severity ratings'],
    milestones: [
      { id: 1, title: 'Automated scan & initial findings', pct: 30, dueWeek: 1 },
      { id: 2, title: 'Manual deep review',                pct: 40, dueWeek: 2 },
      { id: 3, title: 'Final report & remediation guide',  pct: 30, dueWeek: 3 },
    ],
    projectOwnerName: 'OmniLend Finance',
    projectOwnerVerified: true,
    myStatus: null,
  },
  {
    id: 'mk_003',
    title: 'DAO Governance Dashboard',
    category: 'Engineering',
    description: 'Build a governance dashboard that indexes on-chain proposal data via The Graph and renders voting history, quorum progress, and delegate profiles. React + TypeScript.',
    budgetUsd: 6200,
    paymentStructure: 'full',
    chain: 'base',
    requiredType: 'both',
    deadline: new Date(Date.now() + 1000*60*60*24*25).toISOString(),
    applicantCount: 9,
    kpis: ['The Graph', 'React/TS', 'On-chain indexing', 'Delegate profiles'],
    milestones: [],
    projectOwnerName: 'MetaGov DAO',
    projectOwnerVerified: false,
    myStatus: null,
  },
  {
    id: 'mk_004',
    title: 'Web3 Brand Identity & Design System',
    category: 'Design',
    description: 'Create a full brand identity (logo, typography, colour system) and a Figma component library for a new DeFi yield aggregator. Deliverables include brand guidelines PDF and developer handoff kit.',
    budgetUsd: 5800,
    paymentStructure: 'milestone',
    chain: 'solana',
    requiredType: 'individual',
    deadline: new Date(Date.now() + 1000*60*60*24*21).toISOString(),
    applicantCount: 22,
    kpis: ['Figma', 'Brand guidelines', 'Component library', 'Dev handoff'],
    milestones: [
      { id: 1, title: 'Mood board & brand direction',     pct: 25, dueWeek: 1 },
      { id: 2, title: 'Logo + type system finalised',     pct: 35, dueWeek: 3 },
      { id: 3, title: 'Full Figma component library',     pct: 40, dueWeek: 5 },
    ],
    projectOwnerName: 'YieldVault',
    projectOwnerVerified: true,
    myStatus: null,
  },
  {
    id: 'mk_005',
    title: 'Protocol Growth & Community Strategy',
    category: 'Community & Growth',
    description: 'Build and execute a 3-month growth strategy for a Base-native NFT marketplace. Includes Twitter/X management, Discord moderation, ambassador programme setup, and weekly reporting.',
    budgetUsd: 4200,
    paymentStructure: 'milestone',
    chain: 'base',
    requiredType: 'pod',
    deadline: new Date(Date.now() + 1000*60*60*24*30).toISOString(),
    applicantCount: 31,
    kpis: ['Twitter/X', 'Discord', 'Ambassador programme', 'Weekly reports'],
    milestones: [
      { id: 1, title: 'Strategy doc & channel setup',     pct: 20, dueWeek: 2 },
      { id: 2, title: 'Month 1 execution + first report', pct: 40, dueWeek: 6 },
      { id: 3, title: 'Month 2–3 + final report',         pct: 40, dueWeek: 12 },
    ],
    projectOwnerName: 'MintHaus',
    projectOwnerVerified: false,
    myStatus: null,
  },
  {
    id: 'mk_006',
    title: 'On-Chain Analytics & TVL Reporting',
    category: 'Research',
    description: 'Build a weekly on-chain analytics report covering protocol TVL, wallet cohort analysis, and yield comparisons across Base DeFi protocols. Deliverable: automated Dune dashboard + written brief.',
    budgetUsd: 3900,
    paymentStructure: 'full',
    chain: 'base',
    requiredType: 'individual',
    deadline: new Date(Date.now() + 1000*60*60*24*14).toISOString(),
    applicantCount: 11,
    kpis: ['Dune Analytics', 'Cohort analysis', 'TVL tracking', 'Written brief'],
    milestones: [],
    projectOwnerName: 'Chain Analytics Guild',
    projectOwnerVerified: true,
    myStatus: null,
  },
  {
    id: 'mk_007',
    title: 'Solana Wallet Integration & SDK',
    category: 'Engineering',
    description: 'Integrate Phantom, Backpack and Solflare wallets into an existing React dApp using @solana/wallet-adapter. Includes transaction signing, SPL token support, and error-state handling.',
    budgetUsd: 7100,
    paymentStructure: 'milestone',
    chain: 'solana',
    requiredType: 'both',
    deadline: new Date(Date.now() + 1000*60*60*24*12).toISOString(),
    applicantCount: 6,
    kpis: ['Phantom', 'Backpack', 'Solflare', 'SPL tokens'],
    milestones: [
      { id: 1, title: 'Wallet adapter setup + Phantom', pct: 35, dueWeek: 1 },
      { id: 2, title: 'Backpack + Solflare + SPL',      pct: 40, dueWeek: 2 },
      { id: 3, title: 'Error handling + final tests',   pct: 25, dueWeek: 3 },
    ],
    projectOwnerName: 'Solrise Finance',
    projectOwnerVerified: true,
    myStatus: null,
  },
  {
    id: 'mk_008',
    title: 'Content Strategy & Technical Writing',
    category: 'Content',
    description: 'Write a 12-piece technical blog series explaining how a new L2 ZK-rollup works, targeted at intermediate Web3 developers. Each piece 1,500–2,000 words, SEO-optimised, with diagrams.',
    budgetUsd: 3200,
    paymentStructure: 'milestone',
    chain: 'base',
    requiredType: 'individual',
    deadline: new Date(Date.now() + 1000*60*60*24*40).toISOString(),
    applicantCount: 18,
    kpis: ['Technical writing', 'SEO', 'Diagrams', '12 articles'],
    milestones: [
      { id: 1, title: 'Outline + first 4 articles',   pct: 35, dueWeek: 3 },
      { id: 2, title: 'Articles 5–8',                 pct: 30, dueWeek: 6 },
      { id: 3, title: 'Articles 9–12 + final edits',  pct: 35, dueWeek: 9 },
    ],
    projectOwnerName: 'zkLayer',
    projectOwnerVerified: false,
    myStatus: null,
  },
  {
    id: 'mk_009',
    title: 'Go-to-Market Strategy for DeFi Launch',
    category: 'Strategy & GTM',
    description: 'Develop a full GTM playbook for a new perpetuals DEX launching on Base. Includes competitive analysis, target user segments, launch sequencing, KPI framework, and PR/influencer outreach plan.',
    budgetUsd: 5500,
    paymentStructure: 'milestone',
    chain: 'base',
    requiredType: 'pod',
    deadline: new Date(Date.now() + 1000*60*60*24*20).toISOString(),
    applicantCount: 8,
    kpis: ['Competitive analysis', 'GTM playbook', 'KPI framework', 'PR plan'],
    milestones: [
      { id: 1, title: 'Market research & positioning',  pct: 30, dueWeek: 2 },
      { id: 2, title: 'GTM playbook v1',                pct: 40, dueWeek: 4 },
      { id: 3, title: 'Final deck & outreach list',     pct: 30, dueWeek: 5 },
    ],
    projectOwnerName: 'PerpVault',
    projectOwnerVerified: true,
    myStatus: null,
  },
  {
    id: 'mk_010',
    title: 'DevOps & CI/CD Pipeline Setup',
    category: 'DevOps',
    description: 'Set up a full CI/CD pipeline for a multi-contract Solidity project using GitHub Actions, Hardhat, and Slither. Includes automated test runs, coverage reports, and deployment to Base Sepolia.',
    budgetUsd: 4800,
    paymentStructure: 'full',
    chain: 'base',
    requiredType: 'individual',
    deadline: new Date(Date.now() + 1000*60*60*24*9).toISOString(),
    applicantCount: 5,
    kpis: ['GitHub Actions', 'Hardhat', 'Slither', 'Base Sepolia'],
    milestones: [],
    projectOwnerName: 'BuilderDAO',
    projectOwnerVerified: false,
    myStatus: null,
  },
]
