export const MOCK_USER = {
  id: 'user_001',
  username: 'Samuelegin',
  displayName: 'Samuel Egin',
  email: 'samuelegin@gmail.com',
  avatarUrl: null,
  bio: 'Full-stack Web3 developer. Solidity + React. Building on Base.',
  roleTags: ['Lead Engineer', 'Smart Contract Dev'],
  skillTags: ['Solidity', 'React', 'Node.js', 'TypeScript', 'DeFi'],
  baseWallet: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
  solanaWallet: null,
  socials: { twitter: 'samuel', github: 'samuelein', telegram: 'samuelegin' },
  blueTick: false,
  goldTick: false,
  kycVerified: false,
  totalEarningsUsd: 12450,
  reputationScore: 94,
  totalPops: 7,
  socials: { twitter: 'samuel', github: 'samuelegin' },
}

export const MOCK_PODS = [
  {
    id: 'pod_001',
    name: 'DeFi Builders',
    description: 'A tight pod of 3 building DeFi primitives on Base.',
    status: 'active',
    myRole: 'admin',
    memberCount: 3,
    reputationScore: 91,
    popCount: 4,
    earningsUsd: 8200,
    maxMembers: 5,
    settlementChain: 'base',
    roles: ['Lead Engineer', 'Smart Contract Dev', 'UI Designer'],
    splits: [
      { role: 'Lead Engineer',       percentage: 50 },
      { role: 'Smart Contract Dev',  percentage: 30 },
      { role: 'UI Designer',         percentage: 20 },
    ],
    members: [
      { id: 'user_001', displayName: 'Samuel',    role: 'Lead Engineer',      isAdmin: true,  reputationScore: 94, popCount: 4 },
      { id: 'user_002', displayName: 'Maliel',   role: 'Smart Contract Dev', isAdmin: false, reputationScore: 88, popCount: 3 },
      { id: 'user_003', displayName: 'Josh',      role: 'UI Designer',        isAdmin: false, reputationScore: 82, popCount: 2 },
    ],
    popRecords: [
      { id: 'pr_a1', workType: 'Engineering', jobTitle: 'DEX Frontend Redesign', milestones: 3, delivery: 'On time', chainAnchor: 'Base', score: 95, issuedAt: '2026-01-15T00:00:00Z' },
    ],
    projectAssigned: true,
    createdAt: '2025-09-10T10:00:00Z',
    deals: [
      { id: 'deal_001', title: 'DEX Frontend Redesign',      status: 'active',    budgetUsd: 4500, category: 'Engineering', timeline: '6 weeks' },
      { id: 'deal_002', title: 'Smart Contract Audit',        status: 'pending',   budgetUsd: 3700, category: 'Engineering', timeline: '2 weeks' },
      { id: 'deal_003', title: 'Liquidity Pool UI',           status: 'completed', budgetUsd: 2800, category: 'Design',      timeline: '4 weeks' },
    ],
  },
  {
    id: 'pod_002',
    name: 'DAO Content Crew',
    description: 'Community growth and content strategy for Web3 protocols.',
    status: 'forming',
    myRole: 'member',
    memberCount: 2,
    reputationScore: null,
    popCount: 0,
    earningsUsd: 0,
    maxMembers: 4,
    settlementChain: 'solana',
    roles: ['Content Strategist', 'Community Lead'],
    splits: [
      { role: 'Content Strategist', percentage: 55 },
      { role: 'Community Lead',     percentage: 45 },
    ],
    members: [
      { id: 'user_004', displayName: 'Sensei',   role: 'Content Strategist', isAdmin: true,  reputationScore: 79, popCount: 2 },
      { id: 'user_001', displayName: 'Maliel',    role: 'Community Lead',     isAdmin: false, reputationScore: 94, popCount: 4 },
    ],
    projectAssigned: false,
    createdAt: '2025-11-20T10:00:00Z',
    deals: [],
  },
  {
    id: 'pod_003',
    name: 'Chain Analytics',
    description: 'On-chain data analysis and dashboards for protocols.',
    status: 'completed',
    myRole: 'admin',
    memberCount: 3,
    reputationScore: 96,
    popCount: 5,
    earningsUsd: 11800,
    maxMembers: 3,
    settlementChain: 'base',
    roles: ['Lead Engineer', 'Research Analyst', 'DevOps'],
    splits: [
      { role: 'Lead Engineer',    percentage: 45 },
      { role: 'Research Analyst', percentage: 35 },
      { role: 'DevOps',           percentage: 20 },
    ],
    members: [
      { id: 'user_001', displayName: 'Samuel',      role: 'Lead Engineer',    isAdmin: true,  reputationScore: 94, popCount: 4 },
      { id: 'user_005', displayName: 'Josh',         role: 'Research Analyst', isAdmin: false, reputationScore: 85, popCount: 3 },
      { id: 'user_006', displayName: 'Maliel',      role: 'DevOps',           isAdmin: false, reputationScore: 80, popCount: 2 },
    ],
    popRecords: [
      { id: 'pr_c1', workType: 'Research',    jobTitle: 'Protocol TVL Dashboard', milestones: 3, delivery: 'On time', chainAnchor: 'Base', score: 96, issuedAt: '2025-11-15T00:00:00Z' },
      { id: 'pr_c2', workType: 'Research',    jobTitle: 'Wallet Flow Analytics',  milestones: 2, delivery: 'Early',   chainAnchor: 'Base', score: 94, issuedAt: '2025-10-02T00:00:00Z' },
      { id: 'pr_c3', workType: 'Engineering', jobTitle: 'DEX Smart Contracts',    milestones: 4, delivery: 'On time', chainAnchor: 'Base', score: 91, issuedAt: '2025-08-20T00:00:00Z' },
    ],
    projectAssigned: false,
    createdAt: '2025-06-01T10:00:00Z',
    deals: [
      { id: 'deal_009', title: 'Protocol TVL Dashboard', status: 'completed', budgetUsd: 6000, category: 'Research', timeline: '5 weeks' },
      { id: 'deal_010', title: 'Wallet Flow Analytics',  status: 'completed', budgetUsd: 5800, category: 'Research', timeline: '4 weeks' },
    ],
  },
]

export const MOCK_DEALS = [
  {
    id: 'deal_001',
    title: 'DEX Frontend Redesign',
    category: 'Engineering',
    description: 'Redesign the trading interface of our DEX. Must support mobile, connect with wagmi, and handle real-time price feeds. Deliverable is a production-ready Next.js app.',
    budgetUsd: 4500,
    paymentStructure: 'milestone',
    chain: 'base',
    requiredType: 'pod',
    matchType: 'manual',
    timeline: '6 weeks',
    deadline: '2026-04-28T00:00:00Z',
    applicantCount: 8,
    kpis: ['Mobile-responsive trading UI', 'Sub-100ms price update latency', 'Passing unit test coverage >80%'],
    milestones: [
      { title: 'Design mockups approved',  description: 'Figma designs reviewed and signed off', amount: 900 },
      { title: 'Core trading UI shipped',  description: 'Connect wallet, swap interface, order book', amount: 2100 },
      { title: 'Mobile + testing done',    description: 'Fully responsive + all tests passing', amount: 1500 },
    ],
    projectOwner: { name: 'BaseSwap Protocol', avatarUrl: null, completedJobs: 12 },
    myStatus: 'accepted',
  },
  {
    id: 'deal_002',
    title: 'Smart Contract Audit — Lending Protocol',
    category: 'Engineering',
    description: 'Security audit for a new lending protocol on Base. Scope includes 4 core contracts. Must deliver a full report with severity ratings and recommended fixes.',
    budgetUsd: 3700,
    paymentStructure: 'full',
    chain: 'base',
    requiredType: 'both',
    matchType: 'system',
    timeline: '2 weeks',
    deadline: '2026-04-15T00:00:00Z',
    applicantCount: 5,
    kpis: ['Full audit report with CVSS scores', 'Re-audit of critical fixes', 'Executive summary for investors'],
    milestones: [],
    projectOwner: { name: 'LendBase Finance', avatarUrl: null, completedJobs: 3 },
    myStatus: 'applied',
  },
  {
    id: 'deal_003',
    title: 'NFT Marketplace UI',
    category: 'Design',
    description: 'Full UI/UX design for an NFT marketplace targeting Web3 newcomers. Figma source files + dev handoff. Light and dark mode required.',
    budgetUsd: 2200,
    paymentStructure: 'full',
    chain: 'solana',
    requiredType: 'individual',
    matchType: 'manual',
    timeline: '3 weeks',
    deadline: '2026-04-20T00:00:00Z',
    applicantCount: 14,
    kpis: ['Complete Figma component library', 'Light + dark mode variants', 'Prototype with interactions'],
    milestones: [],
    projectOwner: { name: 'SolArt Studios', avatarUrl: null, completedJobs: 7 },
    myStatus: null,
  },
  {
    id: 'deal_004',
    title: 'DAO Newsletter & Social Strategy',
    category: 'Community & Growth',
    description: 'Monthly newsletter (4 editions), Twitter/X content calendar (60 posts), and Discord community growth plan. Must have prior DAO experience.',
    budgetUsd: 1800,
    paymentStructure: 'milestone',
    chain: 'solana',
    requiredType: 'both',
    matchType: 'manual',
    timeline: '4 weeks',
    deadline: '2026-05-01T00:00:00Z',
    applicantCount: 22,
    kpis: ['4 newsletter editions published', '60 social posts scheduled', 'Discord member growth >15%'],
    milestones: [
      { title: 'Strategy doc approved',    amount: 400  },
      { title: 'Month 1 content delivered', amount: 700 },
      { title: 'Month 2 content + report', amount: 700  },
    ],
    projectOwner: { name: 'MetaGov DAO', avatarUrl: null, completedJobs: 5 },
    myStatus: null,
  },
  {
    id: 'deal_005',
    title: 'Cross-Chain Bridge Security Review',
    category: 'Engineering',
    description: 'Comprehensive security review of a cross-chain bridge protocol. Includes threat modelling, fuzzing campaign, and formal report. High severity findings will be disclosed responsibly.',
    budgetUsd: 8500,
    paymentStructure: 'milestone',
    chain: 'base',
    requiredType: 'pod',
    matchType: 'system',
    timeline: '3 weeks',
    deadline: '2026-04-10T00:00:00Z',
    applicantCount: 3,
    kpis: ['Threat model document', 'Fuzzing campaign results', 'Final security report'],
    milestones: [
      { title: 'Threat modelling complete', amount: 2500 },
      { title: 'Fuzzing campaign done',     amount: 3000 },
      { title: 'Final report delivered',    amount: 3000 },
    ],
    projectOwner: { name: 'OmniLink Protocol', avatarUrl: null, completedJobs: 2 },
    myStatus: null,
  },
  {
    id: 'deal_006',
    title: 'DeFi Research Report — RWA Landscape',
    category: 'Research',
    description: 'In-depth research into the Real World Assets (RWA) space on-chain. 20-page report covering top 10 protocols, risk analysis, and emerging opportunities.',
    budgetUsd: 1200,
    paymentStructure: 'full',
    chain: 'base',
    requiredType: 'individual',
    matchType: 'manual',
    timeline: '2 weeks',
    deadline: '2026-04-18T00:00:00Z',
    applicantCount: 9,
    kpis: ['20-page report', 'Protocol comparison table', 'Risk matrix'],
    milestones: [],
    projectOwner: { name: 'BaseAlpha Research', avatarUrl: null, completedJobs: 18 },
    myStatus: null,
  },
  {
    id: 'deal_007',
    title: 'Staking Dashboard — Frontend',
    category: 'Engineering',
    description: 'Build a staking dashboard for our LSD protocol. Show APY, validator performance, and reward history. Must integrate with our existing wagmi-based stack.',
    budgetUsd: 3100,
    paymentStructure: 'full',
    chain: 'base',
    requiredType: 'both',
    matchType: 'manual',
    timeline: '4 weeks',
    deadline: '2026-05-10T00:00:00Z',
    applicantCount: 6,
    kpis: ['Live APY display', 'Validator leaderboard', 'Reward claim flow'],
    milestones: [],
    projectOwner: { name: 'StakeBase Labs', avatarUrl: null, completedJobs: 9 },
    myStatus: null,
  },
  {
    id: 'deal_008',
    title: 'Tokenomics Design & Modelling',
    category: 'Strategy & GTM',
    description: 'Design tokenomics for a new L2 governance token. Includes emission schedule, vesting curves, staking rewards, and agent-based simulation model.',
    budgetUsd: 5500,
    paymentStructure: 'milestone',
    chain: 'base',
    requiredType: 'pod',
    matchType: 'system',
    timeline: '3 weeks',
    deadline: '2026-04-25T00:00:00Z',
    applicantCount: 4,
    kpis: ['Token distribution model', 'Emission schedule doc', 'Simulation results'],
    milestones: [
      { title: 'Initial design approved',  amount: 2000 },
      { title: 'Simulation delivered',     amount: 2000 },
      { title: 'Final deck + doc',         amount: 1500 },
    ],
    projectOwner: { name: 'Layer2 Ventures', avatarUrl: null, completedJobs: 6 },
    myStatus: null,
  },
]

export const MOCK_NOTIFICATIONS = [
  { id: 'n1', type: 'job_assigned',    title: 'You were matched to DEX Frontend Redesign',          body: 'BaseSwap Protocol accepted your application. Chat is now open.',   read: false, createdAt: new Date(Date.now() - 1000*60*25).toISOString() },
  { id: 'n2', type: 'funds_released',  title: '$8,200 released to your pod',                        body: 'Chain Analytics completed — payout sent to Base wallet.',          read: false, createdAt: new Date(Date.now() - 1000*60*60*2).toISOString() },
  { id: 'n3', type: 'rating_received', title: 'New 5★ rating from OmniLink Protocol',              body: '"Exceptional quality and communication. Will work again."',          read: false, createdAt: new Date(Date.now() - 1000*60*60*5).toISOString() },
  { id: 'n4', type: 'pod_invite',      title: 'Priya Nair invited you to DAO Content Crew',        body: 'Role: Community Lead · Pod on Solana',                             read: true,  createdAt: new Date(Date.now() - 1000*60*60*24).toISOString() },
  { id: 'n5', type: 'work_approved',   title: 'Deliverable approved — Chain Analytics',            body: 'Your TVL dashboard was approved. PoP badge incoming.',             read: true,  createdAt: new Date(Date.now() - 1000*60*60*48).toISOString() },
  { id: 'n6', type: 'pop_minted',      title: 'PoP Badge #7 minted on Base',                       body: 'On-chain reputation updated. View your Performance Book.',         read: true,  createdAt: new Date(Date.now() - 1000*60*60*72).toISOString() },
  { id: 'n7', type: 'pod_invite',      title: 'DeFi Builders pod — new member joined',             body: 'Mike Torres accepted the UI Designer role.',                       read: true,  createdAt: new Date(Date.now() - 1000*60*60*96).toISOString() },
]

export const MOCK_LEADERBOARD = [
  { id: 'user_007', username: '0xdauxun',   displayName: '0xDauxun',   earned: 38400, completedJobs: 24, reputationScore: 99, blueTick: true,  goldTick: true,  kycVerified: true  },
  { id: 'user_008', username: 'blaqsmith',  displayName: 'Blaqsmith',  earned: 29100, completedJobs: 18, reputationScore: 97, blueTick: true,  goldTick: false, kycVerified: true  },
  { id: 'user_009', username: 'dwarf_web3', displayName: 'Dwarf of Web3', earned: 24800, completedJobs: 15, reputationScore: 96, blueTick: true,  goldTick: false, kycVerified: true  },
  { id: 'user_010', username: 'web3bull',   displayName: 'Web3 Bull',  earned: 19500, completedJobs: 13, reputationScore: 95, blueTick: false, goldTick: false, kycVerified: true  },
  { id: 'user_001', username: 'swyft',      displayName: 'Swyft',      earned: 12450, completedJobs: 9,  reputationScore: 94, blueTick: false, goldTick: false, kycVerified: false },
  { id: 'user_011', username: 'xammie',     displayName: 'Xammie',     earned: 9800,  completedJobs: 7,  reputationScore: 90, blueTick: false, goldTick: false, kycVerified: true  },
  { id: 'user_012', username: 'edosa',      displayName: 'Edosa',      earned: 7600,  completedJobs: 6,  reputationScore: 87, blueTick: false, goldTick: false, kycVerified: false },
  { id: 'user_004', username: '0xxener',    displayName: '0xXener',    earned: 5200,  completedJobs: 5,  reputationScore: 79, blueTick: false, goldTick: false, kycVerified: false },
  { id: 'user_013', username: 'chidi',      displayName: 'Chidi',      earned: 3900,  completedJobs: 4,  reputationScore: 75, blueTick: false, goldTick: false, kycVerified: false },
  { id: 'user_014', username: 'kaito_eth',  displayName: 'Kaito Nakamura', earned: 1800, completedJobs: 2, reputationScore: 68, blueTick: false, goldTick: false, kycVerified: false },
]

export const MOCK_POP_RECORDS = [
  { id: 'pop_001', workType: 'Engineering', jobTitle: 'Protocol TVL Dashboard', milestones: 3, delivery: 'On time', chainAnchor: 'Base', score: '96/100', issuedAt: '2025-11-15T00:00:00Z' },
  { id: 'pop_002', workType: 'Engineering', jobTitle: 'Wallet Flow Analytics',  milestones: 2, delivery: 'Early',   chainAnchor: 'Base', score: '94/100', issuedAt: '2025-10-02T00:00:00Z' },
  { id: 'pop_003', workType: 'Engineering', jobTitle: 'DEX Smart Contracts',    milestones: 4, delivery: 'On time', chainAnchor: 'Base', score: '91/100', issuedAt: '2025-08-20T00:00:00Z' },
  { id: 'pop_004', workType: 'Design',      jobTitle: 'DeFi App Rebrand',       milestones: 2, delivery: 'On time', chainAnchor: 'Base', score: '89/100', issuedAt: '2025-07-10T00:00:00Z' },
]

// Project owner side
export const MOCK_PROJECT = {
  id: 'proj_001',
  displayName: 'BaseSwap Protocol',
  email: 'team@baseswap.io',
  bio: 'Leading DEX on Base. Building the future of on-chain trading.',
  avatarUrl: null,
  baseWallet: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
  socials: { website: 'baseswap.io', twitter: 'baseswap' },
  blueTick: true,
  goldTick: false,
}

export const MOCK_PROJECT_JOBS = [
  {
    id: 'pjob_001',
    title: 'DEX Frontend Redesign',
    category: 'Engineering',
    status: 'active',
    budgetUsd: 4500,
    timeline: '6 weeks',
    matchType: 'manual',
    applicantCount: 8,
    deadline: '2026-04-28T00:00:00Z',
  },
  {
    id: 'pjob_002',
    title: 'Smart Contract Audit — v2',
    category: 'Engineering',
    status: 'open',
    budgetUsd: 3700,
    timeline: '2 weeks',
    matchType: 'system',
    applicantCount: 3,
    deadline: '2026-04-15T00:00:00Z',
  },
  {
    id: 'pjob_003',
    title: 'Liquidity Pool UI',
    category: 'Design',
    status: 'completed',
    budgetUsd: 2800,
    timeline: '4 weeks',
    matchType: 'manual',
    applicantCount: 11,
    deadline: '2026-02-01T00:00:00Z',
  },
  {
    id: 'pjob_004',
    title: 'Tokenomics Research Report',
    category: 'Research',
    status: 'draft',
    budgetUsd: 1500,
    timeline: '2 weeks',
    matchType: 'manual',
    applicantCount: 0,
    deadline: '2026-05-30T00:00:00Z',
  },
]